-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE tasks (
    id SERIAL PRIMARY KEY,
    item text,
    completed boolean DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX tasks_pkey ON tasks(id int4_ops);